name: CI Checks for build

on:
  push:
    branches-ignore:   
      - 'release**'
      - 'main'
      - 'master'

jobs:
  test_build:
    name: Test the Build
    runs-on: ubuntu-latest
    # environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3    
      - name: Setup
        uses: docker/setup-buildx-action@v2
        with:
          install: true  
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: false
      # - name: Checkout repository
      #   uses: actions/checkout@v3      
      # - name: Perform a test build
      #   run: |
      #     docker build -f Dockerfile-local -t testimage .




